version: '3.8'

services:
  api-gateway:
    image: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    environment:
      SPRING_APPLICATION_NAME: "API-GATEWAY"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - internal_network

  accountservice:
    image: accountservice
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: "ACCOUNT-SERVICE"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/accountservice?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    depends_on:
      - db
    networks:
      - internal_network

  service-registry:
    image: service-registry
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: "EUREKA-SERVER"
    networks:
      - internal_network

  customer-service:
    image: customer-service
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: "CUSTOMER-SERVICE"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://db2:3306/customerservice?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    depends_on:
      - db2
    networks:
      - internal_network

  transactionservice:
    image: transactionservice
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: "TransactionService"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://db3:3306/transactionservice?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    depends_on:
      - db3
    networks:
      - internal_network

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: accountservice
      MYSQL_PASSWORD: root@123
    networks:
      - internal_network

  db2:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: customerservice
      MYSQL_PASSWORD: root@123
    networks:
      - internal_network

  db3:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: transactionservice
      MYSQL_PASSWORD: root@123
    networks:
      - internal_network

networks:
  internal_network: